{
 "title": "应用监控",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tomcat - 最大连接数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_connections_config_max_connections{job=\"chatgpt-data-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tomcat - 使用连接数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_connections_current_connections{job=\"chatgpt-data-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tomcat - 最大线程数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tomcat_threads_current_threads{job=\"chatgpt-data-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenAi - 对话 - 日次数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(http_server_requests_seconds_count{uri=\"/api/v1/chatgpt/chat/completions\", method=\"POST\", status=\"200\", exception=\"None\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "下单数量",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(http_server_requests_seconds_count{uri=\"/api/v1/sale/create_pay_order\", method=\"POST\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "支付完成",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method) (changes(http_server_requests_seconds_count{uri=\"/api/v1/sale/create_pay_order\", method=\"POST\"}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "数据库监控",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "hikaricp_connections{pool=\"HikariPool-1\", job=\"x-api-app\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hikaricp_connections_idle{pool=\"HikariPool-1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(hikaricp_connections_acquire_seconds_count{job=\"x-api-app\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(hikaricp_connections_usage_seconds_count{pool=\"HikariPool-1\"}[5m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(hikaricp_connections_max{pool=\"HikariPool-1\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tomcat - 实时连接数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "tomcat_connections_current_connections{job=\"chatgpt-data-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "对话监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "OpenAi - 对话 - 请求量/分",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(uri, exception, job) (increase(http_server_requests_seconds_count{uri=~\"/api/v1/chatgpt/chat/completions\", method=\"POST\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenAi - 对话 - 响应时间/分",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by (uri) (increase(http_server_requests_seconds_sum{uri=~\"/api/v1/chatgpt/chat/completions\"}[1m]))\n/sum by (uri) (increase(http_server_requests_seconds_count{uri=~\"/api/v1/chatgpt/chat/completions\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "下单监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "OpenAi - 商品查询 - 请求量/分钟",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(uri, exception, job) (increase(http_server_requests_seconds_count{uri=\"/api/v1/sale/query_product_list\", method=\"GET\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenAi - 商品查询 - 响应时间/分",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum by(uri) (increase(http_server_requests_seconds_sum{uri=~\"/api/v1/sale/query_product_list\"}[1m])) / sum by(uri) (increase(http_server_requests_seconds_count{uri=~\"/api/v1/sale/query_product_list\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenAi - 商品下单 - 请求量/时",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(job, uri, exception) (increase(http_server_requests_seconds_count{uri=~\"/api/v1/sale/create_pay_order\", method=\"POST\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenAi - 商品下单 - 响应时间/分",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by(uri) (increase(http_server_requests_seconds_sum{uri=~\"/api/v1/sale/create_pay_order\"}[1m])) / sum by(uri) (increase(http_server_requests_seconds_count{uri=~\"/api/v1/sale/create_pay_order\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "登录监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "OpenAi - 登录 - QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/api/v1/auth/login\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenAi - 登录 - 请求量/分",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum by(instance, uri, exception) (increase(http_server_requests_seconds_count{uri=~\"/api/v1/auth/login\", method=\"POST\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}